# Generated by Django 2.2.16 on 2023-05-07 19:05

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230507_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.validate_color], verbose_name='Цвет в HEX'),
        ),
    ]
